"""Create initial tables

Revision ID: c55a6ac1d41f
Revises: 
Create Date: 2026-08-26 19:10:14.330336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c55a6ac1d41f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('journal_ref', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_tei_xml', sa.Text(), nullable=True),
    sa.Column('retraction_status', sa.String(length=50), server_default=sa.text("'unchecked'"), nullable=False),
    sa.Column('retraction_source_url', sa.String(length=500), nullable=True),
    sa.Column('retraction_reason', sa.Text(), nullable=True),
    sa.Column('retraction_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_sha256_hash'), 'papers', ['sha256_hash'], unique=True)
    op.create_index(op.f('ix_papers_status'), 'papers', ['status'], unique=False)
    op.create_index(op.f('ix_papers_uploaded_at'), 'papers', ['uploaded_at'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checklist_version', sa.String(length=20), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_paper_id'), 'audits', ['paper_id'], unique=False)
    op.create_index(op.f('ix_audits_status'), 'audits', ['status'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('verified_via_crossref', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('crossref_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_doi'), 'references', ['doi'], unique=False)
    op.create_index(op.f('ix_references_paper_id'), 'references', ['paper_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_appendix', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_paper_id'), 'sections', ['paper_id'], unique=False)
    op.create_index(op.f('ix_sections_section_type'), 'sections', ['section_type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('present', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('location_hint', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verification_reason', sa.String(length=100), nullable=True),
    sa.Column('fuzzy_match_score', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_audit_id'), 'findings', ['audit_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_item_id'), 'findings', ['item_id'], unique=False)
    op.create_index(op.f('ix_findings_section_id'), 'findings', ['section_id'], unique=False)
    op.create_index(op.f('ix_findings_verified'), 'findings', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_verified'), table_name='findings')
    op.drop_index(op.f('ix_findings_section_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_item_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_audit_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_sections_section_type'), table_name='sections')
    op.drop_index(op.f('ix_sections_paper_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_references_paper_id'), table_name='references')
    op.drop_index(op.f('ix_references_doi'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_audits_status'), table_name='audits')
    op.drop_index(op.f('ix_audits_paper_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_papers_uploaded_at'), table_name='papers')
    op.drop_index(op.f('ix_papers_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_sha256_hash'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
